version: '3.8'

services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5001
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5001:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
      - REDIS_HOST=redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
  postgres:
    image: postgres:16.3
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres