name: Release express-app

on:
  push:
    branches:
      - main

jobs:
  publish-to-docker-hub:
    name: Publish Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./part_3/e-3.1/express-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/express-app:latest